# Generated by Django 2.1.5 on 2019-02-09 07:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccess',
            new_name='UserAccessRequest',
        ),
    ]
