# Generated by Django 2.1.5 on 2019-04-20 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190420_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessrequest',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
