# Generated by Django 2.1.5 on 2019-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datauploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
