# Generated by Django 2.1.5 on 2019-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly_detection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnomalyData',
        ),
    ]
